const ALLOWED_SUBSTRINGS: readonly string[] = [
  "facebookexternalhit",
  "facebot",
  "twitterbot",
  "linkedinbot",
  "slackbot",
  "slack-imgproxy",
  "telegrambot",
  "whatsapp",
  "discordbot",
  "pinterest",
  "embedly",
  "googlebot",
  "bingbot",
  "applebot",
  "viber",
  "redditbot",
  "tumblr",
  "line-crawler",
  "kakaotalk",
  "skype",
  "wechat",
  "flipboard",
  "medium",
  "bitlybot",
  "quora link preview",
]

const BLOCKED_SUBSTRINGS: readonly string[] = [
  
  "adsbot-google",
  "duplexweb-google",
  "feedfetcher-google",
  "google favicon",
  "google producer",
  "google read-aloud",
  "google site-verification",
  "google structured-data-testing-tool",
  "google web preview",
  "google weblight",
  "google-adwords",
  "google-inspectiontool",
  "googleother",
  "googlepagespeed",
  "mediapartners-google",
  "storebot-google",
  "adidxbot",
  "bingpreview",
  "microsoft url control",
  "microsoft-webdav",
  "microsoft-office",
  "ms-office",
  "msnbot",
  "baidu spider",
  "baiduspider",
  "duckassistbot",
  "duckduckbot",
  "exabot",
  "petalbot",
  "qwant",
  "qwantify",
  "seznambot",
  "slurp",
  "sogou",
  "yahoo! cache system",
  "yahoo! slurp",
  "yandex.com/bots",
  "yandexbot",
  "yandexmobilebot",
  
  "facebookbot",
  "facebookcatalog",
  "outbrain",
  "taboolabot",
  
  "ahrefs",
  "ahrefsbot",
  "blexbot",
  "bytespider",
  "dotbot",
  "linkdexbot",
  "mj12bot",
  "moz.com",
  "rogerbot",
  "screaming frog",
  "screamingfrog",
  "semrushbot",
  "serpstatbot",
  "sitebulb",
  "sistrix",
  
  "anthropic-ai",
  "chatgpt",
  "chatgpt-user",
  "claude-web",
  "claudebot",
  "cohere-ai",
  "diffbot",
  "gptbot",
  "meta-externalagent",
  "oai-searchbot",
  "omgili",
  "openai",
  "perplexity",
  "perplexitybot",
  "you.com",
  "youbot",
  
  "archive.org",
  "archive.org_bot",
  "ccbot",
  "commoncrawl",
  "ia_archiver",
  
  "censys",
  "masscan",
  "netcraft",
  "nikto",
  "nmap",
  "shodan",
  "sqlmap",
  "zgrab",
  
  "apache-httpclient",
  "aiohttp",
  "axios",
  "curl/",
  "davclnt",
  "davclient",
  "dirbuster",
  "gobuster",
  "go-http-client",
  "headless",
  "headlesschrome",
  "heritrix",
  "httrack",
  "httpclient",
  "httpx",
  "insomnia",
  "java/",
  "libcurl",
  "libwww",
  "libwww-perl",
  "lighthouse",
  "mechanize",
  "newrelicpinger",
  "node-fetch",
  "nutch",
  "okhttp",
  "perl/",
  "phantomjs",
  "php/",
  "playwright",
  "postman",
  "prerender",
  "puppeteer",
  "python-requests",
  "python-urllib",
  "python/",
  "ruby/",
  "rust/",
  "scrapy",
  "selenium",
  "site24x7",
  "undici",
  "urllib",
  "uptimerobot",
  "webcopier",
  "webdriver",
  "wget",
  "wfuzz",
  "wordpress/",
  
  "amazonbot",
  "daum",
  "megaindex",
  "naverbot",
  "speedy spider",
  "tencentbot",
  "yeti",
  
  "jigsaw",
  "nu validator",
  "validator.w3.org",
  "w3c_validator",
];


const BOTISH_WORD = /\b(bot|crawler|spider|scraper|scraping)\b/i;

export function isBlockedBotUserAgent(rawUa: string | null): boolean {
  const ua = (rawUa ?? "").toLowerCase().trim();
  if (!ua) return true;

  if (ALLOWED_SUBSTRINGS.some((p) => ua.includes(p))) {
    return false;
  }

  if (BLOCKED_SUBSTRINGS.some((p) => ua.includes(p))) {
    return true;
  }

  if (BOTISH_WORD.test(ua)) {
    return true;
  }

  return false;
}
